#SPDX-License-Identifier: MIT-0
---
# tasks file for my_module_role
- name: Create file with specified content
  my_own_namespace.yandex_cloud_elk.my_test:
    path: "{{ file_path }}"
    content: "{{ file_content }}"